### ISSUE TITLE
Is it working?

### ISSUE THREAD

**Issue by UtkarshSingh5474** [nmc9/android_Form_Builder#1]
The last comment was "Initial Non-Working Commit" so i was wondering if it is in working state?

**Comment by nmc9** [comment]
Honestly there is probably a better package out there. But if this does what you are looking for then go for it. The latest commit is in a working state. If you follow the example from the activity class you should get... Something.

 I would fork the repo because I don't intend on updating the package

**Comment by UtkarshSingh5474** [comment]
Thanks for the quick comment. I'll try it out :).
